### PR TITLE
Added resources page

### LINKED ISSUE #26: Add A resource page
Info for adopting pets

Info about covid 

Helpful links and styling the page if u can

### PR DESCRIPTION
**Pull request by MLJBrackett**
Fixes #26

In this branch, I have implemented a resource page that the user read and get a better understanding of Adoption and why to choose it. I have also added links to external sites that talk about adoption including Pet finder (The websites API).

Secondly, I added a quick Covid-19 description and adoption during it, likewise with the other paragraph I added links to external sites that speak about adoption during the pandemic.

Lastly, I added a button that routes to /pets incase after reading this they want to adopt a pet.

I think some of this might also be helpful when we create the /about page for the website...

@redxzeta Let me know what you think and if I missed anything, also let me know if you would prefer me to use target="_blank". This would make it so that when the user clicks on the external link it would open a new tab instead of replacing the current tab (The website). Currently I don't have it targeted at anything but I think it might be better if we target it to blank so the user doesn't lose the website on their tabs list.

### CODE REVIEW

**Comment by redxzeta** [comment]
Very Informative especially with the resources in the site.

Yea I agree with the target blank. Looks excellent

**Comment by redxzeta** [comment]
your css file for btn is kinda affecting the other buttons in the other pages

maybe have it like 
`.resource__container .btn`

**Comment by MLJBrackett** [comment]
@redxzeta Fixed the css and added the target, check it out.

**Comment by redxzeta** [comment]
one more task.
can you add it to the ASPCA link and ` a lot of people decided to adopt a friend.` link

**Comment by MLJBrackett** [comment]
Just fixed it

> 
> 
> one more task.
> can you add it to the ASPCA link and ` a lot of people decided to adopt a friend.` link

Fixed :)

**Pull request merged**
