### PR TITLE
added feature to navigate between all pet photos

### PR DESCRIPTION
**Pull request by Wei-J-Huang**
Fixes[#10 ]

I have added buttons to allow navigation between photos of pet.

### CODE REVIEW

**Comment by redxzeta** [comment]
looks good can u add spacing between the buttons?

**Comment by redxzeta** [comment]
```
<Button variant="primary">Primary</Button>
<Button variant="secondary">Secondary</Button>
```
you could also use the react bootstrap buttons

**Comment by Wei-J-Huang** [comment]
The buttons have been updated to use react bootstrap, I used "primary" for both since having different colors seems a bit odd, spaces in between buttons were also added. Please check it out and let me know how it looks.

**Comment by redxzeta** [comment]
looks good

I was showing an example for the different colors

**Pull request merged**
