### PR TITLE
Added new placeholder image

### LINKED ISSUE #32: Placeholder Image
Maybe a more elegant placeholder image?

image

### PR DESCRIPTION
**Pull request by MLJBrackett**
This pull request Fixes #32

### CODE REVIEW

**Comment by redxzeta** [comment]
looks great

**Comment by MLJBrackett** [comment]
Hello @redxzeta, I have implemented a new placeholder image. After a long time I finally got it working and hopefully it is up to your standards, if not tell me and I will fix it as soon as I can.

In addition to this I had some troubles getting my token to work correctly and in the end I had to replace the code in line 28 of PetType.js

```js
 useEffect(() => {
    const config = {
      headers: { Authorization: `Bearer ${token}` },
    };
```

I had to change `${token}` with my generated token that I ran though a curl command on my terminal.

I don't know if this is a normal issue other contributors have but once I did this the my API requests worked perfectly fine, the error that I was receiving was a CORS issue that was blocking my requests. Just thought I would let you know incase their is something wrong with the code base. (I also see that the automated netlify builds are failing since pull request #28 )


This is what the new placeholder looks like
image

I tried to keep the same style of the website while creating the placeholder.

This is how it looks on the website
[Image from Gyazo](https://gyazo.com/015a34f4b7bd140a96deaa2ef84e6aae)

Thanks for letting me tackle this issue!

**Comment by MLJBrackett** [comment]
> looks great

Thanks!

**Comment by redxzeta** [comment]
netlify build should be fixed. I think the yarn lock file got accidentally deleted

**Pull request merged**
