### PR TITLE
Add bootstrap carousel to gallery

### PR DESCRIPTION
**Pull request by drew5494**
#213

### CODE REVIEW

**Comment by redxzeta** [comment]
oh hey thanks for your contribution
can you set the pr to `paw-dev`

**Comment by redxzeta** [comment]
hey @drew5494  Looks like the snapshot needs to be updated so you could do `yarn test` and update it there

**Comment by drew5494** [comment]
> hey @drew5494 Looks like the snapshot needs to be updated so you could do `yarn test` and update it there

I ran yarn test again but receive an error in petInfo.test.js

**Comment by redxzeta** [comment]
> > hey @drew5494 Looks like the snapshot needs to be updated so you could do `yarn test` and update it there
> 
> I ran yarn test again but receive an error in petInfo.test.js

can u show me the error? you could delete the snapshot in the `__tests__` folder where `petInfo.test.js` is

**Comment by redxzeta** [comment]
@drew5494 whoops looks like I should've mentioned to run `yarn test` to create the new snapshot

**Comment by drew5494** [comment]
I did. It appears to be the same snapshot output @redxzeta 
image

**Comment by redxzeta** [comment]
> I did. It appears to be the same snapshot output @redxzeta image

this is local? if it is wondering if you can download node 16.

**Comment by drew5494** [comment]
thanks. I think its working. @redxzeta

**Pull request merged**
