### PR TITLE
added Contributors section to about page

### PR DESCRIPTION
**Pull request by masayaShinoda**
Added a contributors section with avatars of contributors and a github repo link.

### CODE REVIEW

**Comment by redxzeta** [comment]
looks nice.

Think u could have the github link repo open in a tab and contributors link to their github?

**Comment by masayaShinoda** [comment]
Sure thing. Do I have permission to include my avatar as well?

**Comment by redxzeta** [comment]
Yes

**Comment by masayaShinoda** [comment]
Done

**Comment by redxzeta** [comment]
alright just a couple more fixes

1. Add this to the link `target="_blank" without rel="noreferrer"`

1.  I have been looking at the github api docs and found out you can do a get request to get the list of contributors. 
`https://api.github.com/repos/redxzeta/Awesome-Adoption/contributors`
So you could use `axios` to fetch the data using get request and use `useState` to set the data.

also have the id as the key.

```
 {contributors.map((a) => {
              return 
<img key={a.id} src={a} alt="Contributor Avatar"/ >
          })}
```

1. Making it mobile responsive 

image

it goes over the screen for mobile

**Comment by masayaShinoda** [comment]
Woa I never knew theres a contributor api 😮 
Will work on it asap

**Comment by redxzeta** [comment]
for more information on the docs [github docs](https://docs.github.com/en/free-pro-team@latest/restl)

**Comment by masayaShinoda** [comment]
Hi I think I have addressed the issues. Please have a look.
Thanks for this opportunity to learn how to use APIs and React useState 😄

**Comment by redxzeta** [comment]
just a couple adjustments

- instead of ` const axios = require("axios");`  you could just import it outside where all the imports are `import axios from "axios";`

- put the `fetchData` function in `useEffect` to fix the dependency issue and remove the `console.log`  

```
  useEffect(() => {
    const fetchData = async () => {
      const response = await axios.get(apiUrl);
      setAvatars(response.data);
      console.log(response.data); //dont forget to remove this
    };
    fetchData();
  }, []);
```

- put the contributor url on the github avatar by wrapping with `<a>` and the link of the user `<a href={a.html_url}`.  
```
<a key={a.id} href={a.html_url}>
    <img key={a.id} src={a.avatar_url} alt="Contributor Avatar" />
</a>
```

- Might have to fix the css also since the button has the a tag

great progress

**Comment by redxzeta** [comment]
nice changes

**Pull request merged**
