### PR TITLE
Create 'favorites' section

### PR DESCRIPTION
**Pull request by Zeusjonass**
Hi! This solves the issue #273 <<Create 'favorites' section>>

This new feature allows the user to mark a pet as 'favorite' in the pet view and save it to a list which is saved using localstorage.

Screen Shot 2022-01-12 at 10 36 43

Now, to allow the user to access their list of favorite pets, I added a button in the navbar that includes the number of favorites and that updates in real time.

Screen Shot 2022-01-12 at 10 39 56

Finally, when this heart icon is clicked, the view is displayed with all the pets that are in the favorites list.

* **Note**: The favorites list in localstorage only stores the ids to save space, so when this page is loaded it's necessary to fetch the data.

Screen Shot 2022-01-12 at 10 43 07

This is the view when no favorite pets have been marked

Screen Shot 2022-01-12 at 10 44 10

And this is the view when there was an error fetching the data

Screen Shot 2022-01-12 at 10 46 04

* **Note**: I added the heart icons with _yarn add react-icons_

I hope you like the implementation :) Let me know if you want me to modify something

### CODE REVIEW

**Comment by redxzeta** [comment]
wondering if you can fix the conflicting files, was making adjustments to most of the pages

**Comment by Zeusjonass** [comment]
> wondering if you can fix the conflicting files, was making adjustments to most of the pages

@redxzeta done :)

**Comment by redxzeta** [comment]
> > wondering if you can fix the conflicting files, was making adjustments to most of the pages
> 
> @redxzeta done :)

some formatting issues 
just run `yarn format`

**Comment by Zeusjonass** [comment]
> > > wondering if you can fix the conflicting files, was making adjustments to most of the pages
> > 
> > 
> > @redxzeta done :)
> 
> some formatting issues just run `yarn format`

already did it and it doesn't modify any files :( you know what else it could be?

**Review by redxzeta — CHANGES_REQUESTED** [review]

**Comment by redxzeta** [comment]
> > > > wondering if you can fix the conflicting files, was making adjustments to most of the pages
> > > 
> > > 
> > > @redxzeta done :)
> > 
> > 
> > some formatting issues just run `yarn format`
> 
> already did it and it doesn't modify any files :( you know what else it could be?

hmm i just cloned the branch and it did modify `App.js` and `Petinfo.js`

**Pull request merged**
