### PR TITLE
Adding tests for petInfo

### LINKED ISSUE #208: PetInfo Testing help
Running into some issues in `petinfotest.js`

Trying to test the data in PetInfo to see if it comes up by mocking the request but it gets stuck on the spinner

Switch branch to `paw_tests`  to check it out

### PR DESCRIPTION
**Pull request by rclee91**
Fixes #208 
I made a branch off of the `paw-dev` branch. The data in `petInfo.js` is the one on the `paw-dev` branch and not the `main` branch.

Some of the code in `petInfo.js` originally kept breaking the app, especially when refreshing the page. The problem was some objects returned null. So I added conditions for them. The issue I think is `usePetAuth()` for `tokenHeaders` is async,  and it also affects `useFetch()`, so sometimes not all the data have been loaded when the html elements are rendering. 

Also, `navigate.share` doesn't exist on all browsers. I first tried it on FireFox and it crashed the app, so I added a condition to it as well. 

I used mocked data for simulating data from `useFetch()`. Since its an imported function, I don't think it should be tested in `petInfo`, and should be tested in its model instead.

### CODE REVIEW

**Comment by redxzeta** [comment]
> Fixes #208 I made a branch off of the `paw-dev` branch. The data in `petInfo.js` is the one on the `paw-dev` branch and not the `main` branch.
> 
> Some of the code in `petInfo.js` originally kept breaking the app, especially when refreshing the page. The problem was some objects returned null. So I added conditions for them. The issue I think is `usePetAuth()` for `tokenHeaders` is async, and it also affects `useFetch()`, so sometimes not all the data have been loaded when the html elements are rendering.
> 
> Also, `navigate.share` doesn't exist on all browsers. I first tried it on FireFox and it crashed the app, so I added a condition to it as well.
> 
> I used mocked data for simulating data from `useFetch()`. Since its an imported function, I don't think it should be tested in `petInfo`, and should be tested in its model instead.

Yea nice catch. You think theres a better solution?

**Comment by rclee91** [comment]
> 
> 
> > Fixes #208 I made a branch off of the `paw-dev` branch. The data in `petInfo.js` is the one on the `paw-dev` branch and not the `main` branch.
> > Some of the code in `petInfo.js` originally kept breaking the app, especially when refreshing the page. The problem was some objects returned null. So I added conditions for them. The issue I think is `usePetAuth()` for `tokenHeaders` is async, and it also affects `useFetch()`, so sometimes not all the data have been loaded when the html elements are rendering.
> > Also, `navigate.share` doesn't exist on all browsers. I first tried it on FireFox and it crashed the app, so I added a condition to it as well.
> > I used mocked data for simulating data from `useFetch()`. Since its an imported function, I don't think it should be tested in `petInfo`, and should be tested in its model instead.
> 
> Yea nice catch. You think theres a better solution? Could also mock the api if you want just like in `testServer.js`

I think the main problem is the token for using the api for petFinder, which is hard to simulate (because we all have our own secret tokens)

**Review by redxzeta — CHANGES_REQUESTED** [review]
Getting this error
```
    TypeError: str.replace(...).replaceAll is not a function

      4 |     return str
      5 |       .replace(/(^\w+:|^)\/\//, "")
    > 6 |       .replaceAll("&#039;", "'")
        |        ^
      7 |       .replaceAll("&#39;", "'")
      8 |       .replaceAll("&quot;", '"')
      9 |       .replaceAll("&rsquo;", "'")
      ```

**Comment by rclee91** [comment]
> 
> 
> Getting this error
> 
> ```
>     TypeError: str.replace(...).replaceAll is not a function
> 
>       4 |     return str
>       5 |       .replace(/(^\w+:|^)\/\//, "")
>     > 6 |       .replaceAll("&#039;", "'")
>         |        ^
>       7 |       .replaceAll("&#39;", "'")
>       8 |       .replaceAll("&quot;", '"')
>       9 |       .replaceAll("&rsquo;", "'")
>       ```
> ```

Its happening with the `nameCleaner()` function in the `utils/nameCleaner' model. 
Probably just a problem with older node.js versions.

**Comment by redxzeta** [comment]
> > Getting this error
> > ```
> >     TypeError: str.replace(...).replaceAll is not a function
> > 
> >       4 |     return str
> >       5 |       .replace(/(^\w+:|^)\/\//, "")
> >     > 6 |       .replaceAll("&#039;", "'")
> >         |        ^
> >       7 |       .replaceAll("&#39;", "'")
> >       8 |       .replaceAll("&quot;", '"')
> >       9 |       .replaceAll("&rsquo;", "'")
> >       ```
> > ```
> 
> Its happening with the `nameCleaner()` function in the `utils/nameCleaner` model. Probably just a problem with older node.js versions.
> 
> If you really want it fixed, then I can run on nodejs on older versions, and it'll change the snapshots, but it'll keep the error. It's a problem with `nameCleaner()` and not `petInfo`, so, should be a separate commit or issue.

Hmm should we just remove node 12 in the test

**Comment by rclee91** [comment]
> > > Getting this error
> > > ```
> > >     TypeError: str.replace(...).replaceAll is not a function
> > > 
> > >       4 |     return str
> > >       5 |       .replace(/(^\w+:|^)\/\//, "")
> > >     > 6 |       .replaceAll("&#039;", "'")
> > >         |        ^
> > >       7 |       .replaceAll("&#39;", "'")
> > >       8 |       .replaceAll("&quot;", '"')
> > >       9 |       .replaceAll("&rsquo;", "'")
> > >       ```
> > > ```
> > 
> > 
> > Its happening with the `nameCleaner()` function in the `utils/nameCleaner` model. Probably just a problem with older node.js versions.
> > If you really want it fixed, then I can run on nodejs on older versions, and it'll change the snapshots, but it'll keep the error. It's a problem with `nameCleaner()` and not `petInfo`, so, should be a separate commit or issue.
> 
> Hmm should we just remove node 12 in the test

You can try it. Was there a particular reason why you wanted tests in Node 12x?
Though I suspect `replaceAll` might have problems with some 14+ versions.

**Comment by redxzeta** [comment]
> > > > Getting this error
> > > > ```
> > > >     TypeError: str.replace(...).replaceAll is not a function
> > > > 
> > > >       4 |     return str
> > > >       5 |       .replace(/(^\w+:|^)\/\//, "")
> > > >     > 6 |       .replaceAll("&#039;", "'")
> > > >         |        ^
> > > >       7 |       .replaceAll("&#39;", "'")
> > > >       8 |       .replaceAll("&quot;", '"')
> > > >       9 |       .replaceAll("&rsquo;", "'")
> > > >       ```
> > > > ```
> > > 
> > > 
> > > Its happening with the `nameCleaner()` function in the `utils/nameCleaner` model. Probably just a problem with older node.js versions.
> > > If you really want it fixed, then I can run on nodejs on older versions, and it'll change the snapshots, but it'll keep the error. It's a problem with `nameCleaner()` and not `petInfo`, so, should be a separate commit or issue.
> > 
> > 
> > Hmm should we just remove node 12 in the test
> 
> You can try it. Was there a particular reason why you wanted tests in Node 12x? Though I suspect `replaceAll` might have problems with some 14+ versions.

it was the default when I was setting up github actions. Kinda still new 😅

**Comment by rclee91** [comment]
> > 
> > You can try it. Was there a particular reason why you wanted tests in Node 12x? Though I suspect `replaceAll` might have problems with some 14+ versions.
> 
> it was the default when I was setting up github actions. Kinda still new 😅

Could experiment probably. We're all learning here :D

**Comment by rclee91** [comment]
You're gonna have to approve again, since I had to update the upstream (your `paw-dev` branch) on my end as well.

**Comment by redxzeta** [comment]
looks like i have to remove 14 also

**Comment by rclee91** [comment]
> looks like i have to remove 14 also

Or fix `replaceAll`
But, I have updated the upstream once more.

**Comment by redxzeta** [comment]
> 

oh whoops how to to fix `replaceAll` ?

**Comment by rclee91** [comment]
> > 
> 
> oh whoops how to to fix `replaceAll` ?

It's really up to you? Could just use Node 16.x for workflow tests, and remind any future contributors for this repo to update to whichever the Node version the repo is currently running on.

For `replaceAll` my guess is just to use `replace`
Probably change `.replaceAll("&#039;", "'")`
To something like `.replace(/&#039;/gim, "'")`

**Review by redxzeta — APPROVED** [review]

**Comment by redxzeta** [comment]
@rclee91  thanks for your help! appreciate it

**Pull request merged**
