### PR TITLE
docs: update readme.md

### LINKED ISSUE #437: Docs: Update Readme
- Updated existing screenshot with the current website
- Create a section of the stack being used: React, Tailwind, Supabase, Daisy UI

### PR DESCRIPTION
**Pull request by ManasviGoyal**
fixes #437

### CODE REVIEW

**Comment by ManasviGoyal** [comment]
@redxzeta please check.

**Comment by ManasviGoyal** [comment]
Hi, @redxzeta any specific reason why the checks are failing?

**Comment by redxzeta** [comment]
Add `docs:` in the beginning of pr title

**Comment by ManasviGoyal** [comment]
> Add `docs:` in the beginning of pr title

Done.

**Pull request merged**
