### PR TITLE
Feat pet card

### PR DESCRIPTION
**Pull request by jpacsai**
### Description:
Apply new card design to PetType.js
- create new PetCard.js file
- use it in Home.js and PetType.js
- fix css

### Related issue:
#166

### CODE REVIEW

**Comment by jpacsai** [comment]
@redxzeta could you, please elaborate on what adjustments are needed for mobile exactly?

**Comment by redxzeta** [comment]
@jpacsai 

sorry about that. looks like the card went over

image

Think it might have to deal with this css 

image

**Comment by redxzeta** [comment]
I think it might have to deal with it being a grid after looking into it
```
.petList__container {
  text-align: center;
  display: grid;
  place-items: center;
}
```

**Comment by jpacsai** [comment]
@redxzeta sorry, I haven't spotted that, now it's fixed :)

**Comment by redxzeta** [comment]
@jpacsai  Thanks for your contribution :)

**Pull request merged**
